# Generated by Django 4.0.5 on 2022-06-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogpics')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
