# Generated by Django 4.0.5 on 2022-06-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
    ]
